defaults: &defaults
  :FACEBOOK_KEY: "341031536034250"
  :FACEBOOK_SECRET: "d8ce13ac788d3b00e08e1ad6d4a9546a"
  :GMAIL_USERNAME: "manish.johari@kiwitech.com"
  :GMAIL_PASSWORD: "immanish"
  :APP_DOMAIN: "https://pure-island-7043.herokuapp.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults